name:                wall-e
version:             0.1.0.0
github:              "cloudorz/wall-e"
license:             BSD3
author:              "Cloud"
maintainer:          "cloudcry@gmail.com"
copyright:           "@cloud"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/cloudorz/wall-e#readme>

dependencies:
- base >= 4.7 && < 5
- wreq
- rss-conduit
- atom-conduit >= 0.5
- lens
- xml
- time

library:
  source-dirs: src

executables:
  wall-e-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wall-e

tests:
  wall-e-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wall-e
